### ISSUE TITLE
Library is incompatible with AOT compilation

### ISSUE THREAD

**Issue by yatesco** [qerub/camel-snake-kebab#15]
This isn't really a bug per-se with camel-snake-kebab (which is fab!) but I thought you should know that it doesn't deploy on Tomcat 6/7 or 8 with either JDK 6 or 7.  It fails with `NoClassDefFoundError:camel_snake_kebab/core$__GT_CamelCaseString(wrong name: camel_snake_kebab/core$__GT_camelCaseString)`.

EDIT: it also fails with the downloaded jetty distribution (i.e. building a war and dropping it into jetty/webapps).

Running it through lein repl works fine, it is just something funny with Tomcat and jetty.  Thought you might like to know :).

**Comment by qerub** [comment]
I realized more people than I first expected run into this and therefore created pull request #24 to resolve this issue. Feedback is more than welcome.

**Comment by yatesco** [comment]
I like PascalCase as it is more descriptive with the association to Pascal.
http://en.wikipedia.org/wiki/Snake_case suggests either spinal_case or
screaming_snake_case.

**Comment by qerub** [comment]
`SCREAMING_SNAKE_CASE` would be funny. Any votes against? :full_moon_with_face:

**Comment by yatesco** [comment]
+1 from me.

**Comment by qerub** [comment]
Fixed in master and 0.3.0-SNAPSHOT on Clojars. Will do a proper release this weekend.

**Comment by qerub** [comment]
I've released 0.3.0 now.

**Comment by yatesco** [comment]
Thanks Christoffer.
