### ISSUE TITLE
cljs build error

### ISSUE THREAD

**Issue by huxley-source** [qerub/camel-snake-kebab#27]
I'm using camel-snake-kebab in a cljs project. I get the following error:

WARNING: Use of undeclared Var camel-snake-kebab.internals.alter-name/alter-name

My project.
[org.clojure/clojurescript "0.0-2850" :scope "provided"]
[lein-cljsbuild "1.0.6-SNAPSHOT"]

**Comment by qerub** [comment]
This is a regression introduced with 3bb516c14bea809266b9cad259cfb79ec43072d3. I'm surprised it wasn't caught by the test suite.

I've pushed `[camel-snake-kebab "0.3.1-SNAPSHOT"]` with a fix. I'll do a proper release once I understand why ClojureScript works the way it does wrt. to macros and dependencies.

**Comment by qerub** [comment]
I've released 0.3.1 now. Thanks for reporting this issue!
