### ISSUE TITLE
Dev deps leaked into pom in 0.3.x

### ISSUE THREAD

**Issue by gfredericks** [qerub/camel-snake-kebab#32]
cljx, nrepl, clojurescript-test, etc. are declared as runtime dependencies in the deployed poms for at least 0.3.0 and 0.3.1. I'm not sure why.

**Comment by qerub** [comment]
I've checked https://clojars.org/repo/camel-snake-kebab/camel-snake-kebab/0.3.0/camel-snake-kebab-0.3.0.pom and https://clojars.org/repo/camel-snake-kebab/camel-snake-kebab/0.3.1/camel-snake-kebab-0.3.1.pom.

`clojurescript.test` and `tools.nrepl` have `<scope>test</scope>` so I'm not sure what you're saying. Can you provide some more details?

**Comment by gfredericks** [comment]
whoops I forgot test things can be harmlessly in the pom that way. okay so backtracking to the original cause, I noticed a cljx exclusion in a `project.clj`. Apparently what happens if you remove the exclusion is you get this warning from `lein deps :tree`:

```
WARNING!!! version ranges found for:
[camel-snake-kebab "0.3.0"] -> [com.keminglabs/cljx "0.4.0"] -> [org.clojars.trptcolin/sjacket "0.1.0.6"] -> [org.clojure/clojure "[1.3.0,)"]
Consider using [camel-snake-kebab "0.3.0" :exclusions [org.clojure/clojure]].
[camel-snake-kebab "0.3.0"] -> [com.keminglabs/cljx "0.4.0"] -> [org.clojars.trptcolin/sjacket "0.1.0.6"] -> [net.cgrand/regex "1.1.0"] -> [org.clojure/clojure "[1.2.0,)"]
Consider using [camel-snake-kebab "0.3.0" :exclusions [org.clojure/clojure]].
[camel-snake-kebab "0.3.0"] -> [com.keminglabs/cljx "0.4.0"] -> [org.clojars.trptcolin/sjacket "0.1.0.6"] -> [net.cgrand/parsley "0.9.1"] -> [org.clojure/clojure "[1.2.0,)"]
Consider using [camel-snake-kebab "0.3.0" :exclusions [org.clojure/clojure]].
[camel-snake-kebab "0.3.0"] -> [com.keminglabs/cljx "0.4.0"] -> [org.clojars.trptcolin/sjacket "0.1.0.6"] -> [net.cgrand/parsley "0.9.1"] -> [net.cgrand/regex "1.1.0"] -> [org.clojure/clojure "[1.2.0,)"]
Consider using [camel-snake-kebab "0.3.0" :exclusions [org.clojure/clojure]].
```

I don't really know what it means though. It's certainly not a big blocker for me, just a bit of `project.clj` noise.

**Comment by qerub** [comment]
OK, that issue will disappear once I update cljx (issue #28).

**Comment by gfredericks** [comment]
Okay cool, sorry for the noise!

**Comment by qerub** [comment]
No problem! :smiley_cat:
