### ISSUE TITLE
library bring transitive dep on old clojure version

### ISSUE THREAD

**Issue by timothypratley** [qerub/camel-snake-kebab#33]
[camel-snake-kebab "0.3.1"] -> [com.keminglabs/cljx "0.4.0"] -> [org.clojars.trptcolin/sjacket "0.1.0.6"] -> [org.clojure/clojure "[1.3.0,)"]

Consider using [camel-snake-kebab "0.3.1" :exclusions [org.clojure/clojure]]

please in your project.clj exclude clojure from cljx

**Comment by qerub** [comment]
This has already been resolved in `master` by updating `cljx`. Can you take a look at `master`/`0.3.2-SNAPSHOT` (available at Clojars) and see if you're happy with it? If so, I'll do a release tomorrow.

**Comment by timothypratley** [comment]
Tested and confirmed. Thank you.

**Comment by qerub** [comment]
Thanks! Since I'm still awake anyway; 0.3.2 has been released. :)
