### ISSUE TITLE
README version is not on Clojars

### ISSUE THREAD

**Issue by arichiardi** [qerub/camel-snake-kebab#48]
Latest version uploaded was `0.4.0` it seems.

Thanks for the lib! :wink:

**Comment by qerub** [comment]
The `master` branch is for development and I haven't seen a reason to publish snapshot versions by default for this project. If you check the `stable` branch or any release tag you can see that the README version has a corresponding artifact published to Clojars.

I'm planning to resolve this confusion by making a simple web site that will show the currently latest version and act as main documentation source (issue #52).
